---
version: 2

plan:
  key: OPS
  name: Your Plan Name
  project-key: ON
triggers:
  - polling:
      period: 180

variables:
  - foo: bar

stages:
  - name: PRE-BUILD
    jobs:
      - job:
          key: JOB2
          name: First Echo Message
          script:
            - echo "THIS IS THE FIRST MESSAGE!!!!!!."
  - name: BUILD
    jobs:
      - job:
          key: JOB1
          name: Echo Message
          script:
            - echo "Hello DEPLOYMENT, HELLO, DEPLOYMENT"
