---
version: 2

plan:
  key: OPS
  name: DEPLOYMENT
  project-key: ON
triggers:
  - polling:
      period: 180

variables:
  - foo: bar

stages:
  - PRE-BUILD:
      jobs:
        - PRE-BUILD-JOB:
            key: JOB
            name: JUST ECHOING
            script:
              - echo "DEPLOYMENT!!! DEPLOYMENT!!!!"
