---
version: 2
plan:
  project-key: ON
  plan-key: OPS
  name: Deployment Bamboo Pipeline

stages:
  - name: Deployment  # <-- Make sure to include the 'name' property
    jobs:
      - job: EchoBuild
        tasks:
          - script:
              - echo "Building the project..."

  - name: Deploy  # <-- Make sure to include the 'name' property
    jobs:
      - job: EchoDeploy
        tasks:
          - script:
              - echo "Deploying the project..."
